# Generated by Django 2.2 on 2019-04-30 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agapanto_portfolios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('archived', 'archived'), ('removed_by_user', 'removed_by_user'), ('removed_by_admin', 'removed_by_admin'), ('removed_automatically', 'removed_automatically')], default='active', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('current_status', models.CharField(choices=[('hidden', 'hidden'), ('published', 'published')], max_length=32)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agapanto_portfolios.Portfolio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
