# Generated by Django 2.2 on 2019-04-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agapanto_portfolios', '0002_portfolioitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='read_access',
            field=models.CharField(choices=[('owner', 'owner'), ('group', 'group'), ('public', 'public')], default='group', max_length=32),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='write_access',
            field=models.CharField(choices=[('owner', 'owner'), ('group', 'group'), ('public', 'public')], default='group', max_length=32),
        ),
    ]
