# Generated by Django 2.2 on 2019-04-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agapanto_portfolios', '0003_auto_20190430_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='current_status',
            field=models.CharField(choices=[('unpublished', 'unpublished'), ('published', 'published')], max_length=32),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='current_status',
            field=models.CharField(choices=[('unpublished', 'unpublished'), ('published', 'published')], max_length=32),
        ),
    ]
