# Generated by Django 2.2 on 2019-04-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agapanto_portfolios', '0004_auto_20190430_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='current_status',
            field=models.CharField(choices=[('unpublished', 'unpublished'), ('published', 'published')], default='unpublished', max_length=32),
        ),
    ]
