# Generated by Django 2.2 on 2019-05-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agapanto_portfolios', '0007_auto_20190430_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
