# Generated by Django 2.2 on 2019-05-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agapanto_portfolios', '0009_auto_20190513_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
