# Generated by Django 3.1.3 on 2020-12-20 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agapanto_portfolios', '0010_portfolioitem_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='current_status',
            field=models.CharField(choices=[('unpublished', 'unpublished'), ('published', 'published'), ('archived', 'archived')], default='unpublished', max_length=32),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='current_status',
            field=models.CharField(choices=[('unpublished', 'unpublished'), ('published', 'published'), ('archived', 'archived')], max_length=32),
        ),
    ]
