# Generated by Django 3.1.3 on 2020-12-20 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agapanto_portfolios', '0012_auto_20201220_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='write_access',
            field=models.CharField(choices=[('owner', 'owner'), ('group', 'group'), ('authenticated', 'authenticated')], default='group', max_length=32),
        ),
    ]
